# as we mentioned in issue description had a workflow
# like this when developer push on branch main
# is the last check an monitoring code in deployment process
# @link [see doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
name: CD

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: build
        run: pnpm build

      - name: deploy
        run: pnpm deploy
